build_from:
  aarch64: "ghcr.io/sondregronas/ankermake-m5-protocol:v1.2.2"
  amd64: "ghcr.io/sondregronas/ankermake-m5-protocol:v1.2.2"
  armv7: "ghcr.io/sondregronas/ankermake-m5-protocol:v1.2.2"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ankerctl"
  org.opencontainers.image.description: "ankerctl"
  org.opencontainers.image.source: "https://github.com/sondregronas/ankermgmt-hassio-addons"
  org.opencontainers.image.licenses: "GPLv3"