build_from:
  aarch64: "ghcr.io/sondregronas/ankermake-m5-protocol:"
  amd64: "ghcr.io/sondregronas/ankermake-m5-protocol:"
  armv7: "ghcr.io/sondregronas/ankermake-m5-protocol:"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ankerctl"
  org.opencontainers.image.description: "ankerctl"
  org.opencontainers.image.source: "https://github.com/sondregronas/ankermgmt-hassio-addons"
  org.opencontainers.image.licenses: "GPLv3"