build_from:
  aarch64: "https://github.com/sondregronas/ankermake-m5-protocol.git#patch-exiles-1.1-auto-restart-on-failure"
  amd64: "https://github.com/sondregronas/ankermake-m5-protocol.git#patch-exiles-1.1-auto-restart-on-failure"
  armv7: "https://github.com/sondregronas/ankermake-m5-protocol.git#patch-exiles-1.1-auto-restart-on-failure"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ankerctl"
  org.opencontainers.image.description: "ankerctl"
  org.opencontainers.image.source: "https://github.com/sondregronas/ankermgmt-hassio-addons"
  org.opencontainers.image.licenses: "GPLv3"
