name: "ankerctl"
description: "An unofficial fork of the ankerctl addon by sondregronas"
version: "v1.2.2"
slug: "ankerctl"
ingress: true
ingress_port: 4470
ingress_stream: true
ingress_url: "ankerctl"
panel_icon: "mdi:printer-3d"
init: true
host_network: true
map:
  - config:rw
options:
  flask_host: "0.0.0.0"
schema:
  flask_host: str
arch:
  - aarch64
  - amd64
  - armv7
ports:
  4470/tcp: 4470
ports_description:
  4470/tcp: "The webinterface for ankerctl"
