name: "ankerctl"
description: "The official ankerctl addon"
version: "v1.2.1"
slug: "ankerctl"
ingress: false
ingress_port: 4470
ingress_url: "/ankerctl"
ingress_stream: true
init: true
host_network: true
map:
  - config:rw
options:
  flask_host: "0.0.0.0"
schema:
  flask_host: str
arch:
  - aarch64
  - amd64
  - armv7
ports:
  4470/tcp: 4470
ports_description:
  4470/tcp: "The webinterface for ankerctl"
