name: "ankerctl"
description: "An unofficial fork of the ankerctl addon by sondregronas"
version: ""
slug: "ankerctl"
ingress: false  # broken
ingress_port: 4470
ingress_stream: true
panel_icon: "mdi:printer-3d"
init: true
host_network: true
map:
  - config:rw
options:
  flask_host: "0.0.0.0"
schema:
  flask_host: str
arch:
  - aarch64
  - amd64
  - armv7
ports:
  4470/tcp: 4470
ports_description:
  4470/tcp: "The webinterface for ankerctl"
